package org.adso.minimarket.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_EXPIRED,
    AUTH_UNAUTHORIZED,
    VALIDATION_FAILED,
    VALIDATION_CONSTRAINT_VIOLATION,
    VALIDATION_ATTRIBUTE_FAILED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    BUSINESS_INSUFFICIENT_STOCK,
    BUSINESS_INVENTORY_INVALID_ADJUSTMENT,
    BUSINESS_EMPTY_CART,
    BUSINESS_INVALID_OPERATION,
    SERVER_INTERNAL_ERROR,
    SERVER_DATABASE_ERROR
}
